In [1]:
import pandas as pd
import numpy as np
np.random.seed(10)

In [2]:
all_df = pd.read_table("data/SO_train.tsv", sep = "\t")
all_df[:2]

url  urlid  \
0  http://www.bloomberg.com/news/2010-12-23/ibm-p...   4042   
1  http://www.popsci.com/technology/article/2012-...   8471   

                                         boilerplate alchemy_category  \
0  {"title":"IBM Sees Holographic Calls Air Breat...         business   
1  {"title":"The Fully Electronic Futuristic Star...       recreation   

  alchemy_category_score  avglinksize  commonlinkratio_1  commonlinkratio_2  \
0               0.789131     2.055556           0.676471           0.205882   
1               0.574147     3.677966           0.508021           0.288770   

   commonlinkratio_3  commonlinkratio_4  ...    is_news  lengthyLinkDomain  \
0           0.047059           0.023529  ...          1                  1   
1           0.213904           0.144385  ...          1                  1   

   linkwordscore  news_front_page  non_markup_alphanum_characters  \
0             24                0                            5424   
1             40                0                            4973   

   numberOfLinks  numwords_in_url parametrizedLinkRatio  \
0            170                8              0.152941   
1            187                9              0.181818   

   spelling_errors_ratio  label  
0               0.079130      0  
1               0.125448      1  

[2 rows x 27 columns]

In [3]:
useful_df = all_df[(all_df != "?").all(axis=1)]
useful_df

url  urlid  \
0     http://www.bloomberg.com/news/2010-12-23/ibm-p...   4042   
1     http://www.popsci.com/technology/article/2012-...   8471   
2     http://www.menshealth.com/health/flu-fighting-...   1164   
3     http://www.dumblittleman.com/2007/12/10-foolpr...   6684   
4     http://bleacherreport.com/articles/1205138-the...   9006   
6     http://gofashionlane.blogspot.tw/2012/06/ameri...   8685   
10                              http://www.reuters.com/   2293   
12    http://www.ivillage.com/our-dirty-mouths/4-b-1...   1917   
16    http://theawesomer.com/liquid-mountaineering/3...   9842   
17    http://www.guardian.co.uk/fashion/gallery/2012...   3946   
18    http://sugarcrafter.net/2011/06/06/grilled-pea...    334   
19    http://www.ivillage.com/bathroom-degrunge-your...    271   
20    http://www.tmz.com/2012/12/20/olympic-soccer-a...   6984   
25    http://www.midwestsportsfans.com/2010/10/early...   1499   
26                         http://breakingnewsblog.com/   7298   
31    http://www.savvyeat.com/whole-wheat-chocolate-...   2152   
34    http://www.epicurious.com/articlesguides/holid...    497   
37            http://www.collegehumor.com/video:1806201   1650   
41                         http://canarygirl.com/?p=302   4064   
43    http://www.everydayhealth.com/high-cholesterol...    383   
45                    http://amdb10k.net/breaking-news/   5053   
50    http://www.baur.de/content/tunk/categories/jea...   6657   
51    http://www.yummymummyclub.ca/food/recipes/best...   4763   
53    http://laphemmephoodie.com/2011/02/peanut-butt...   8579   
54    http://www.usatoday.com/news/health/story/2012...   3880   
56    http://www.marcandangel.com/2010/03/22/9-timel...   6006   
58                              http://www.cbsnews.com/   9259   
59                           http://www.1001recipe.com/   1656   
61    http://www.bannedinhollywood.com/banneds-after...  10530   
62    http://mysuperchargedlife.com/blog/20-ways-to-...   8262   
...                                                 ...    ...   
7329  http://www.technewsdaily.com/7-ordinary-things...   2996   
7331                            http://espn.go.com/nba/   4097   
7340  http://www.foxnews.com/health/2011/12/01/holid...   9371   
7341  http://www.pcgerms.com/this-dress-shirt-design...   5309   
7342  http://bleacherreport.com/articles/1179008-the...   8312   
7346  http://bleacherreport.com/articles/1223953-100...   8040   
7347  http://www.geek.com/articles/geek-cetera/att-d...   1504   
7348  http://www.laweekly.com/slideshow/la-people-20...   3399   
7349  http://confessionsoftart.blogspot.com/2009/03/...   6252   
7351  http://gizmodo.com/5938338/3dprinted-table-lam...   2912   
7352  http://cookiesandcups.com/spooky-eyes-pretzel-...   9775   
7354  http://www.villagevoice.com/bestof/2007/award/...   9149   
7355  http://www.recipegirl.com/2007/04/10/the-adult...   9277   
7359  http://content.usatoday.com/communities/gameon...     96   
7360  http://5secondrule.typepad.com/my_weblog/2010/...   7532   
7362  http://www.belldinifashions.com/blog/2012/05/3...   5211   
7364            http://dearcrissy.com/lip-balm-recipes/   8891   
7372  http://dornob.com/get-the-lead-out-cartridge-f...   3566   
7373                            http://blog.khymos.org/   3788   
7374  http://www.guardian.co.uk/fashion/gallery/2012...   7485   
7375                   http://www.whatmegansmaking.com/   7425   
7377  http://www.forbes.com/sites/greatspeculations/...  10509   
7379  http://www.savoringthethyme.com/2011/08/toaste...   7696   
7382  http://www.allthingscupcake.com/2007/12/05/mou...   8327   
7383                  http://randomrr.com/80s-kids.html  10126   
7387  http://achicdirection.com/2012/01/23/vintage-f...  10382   
7388  http://www.villagevoice.com/bestof/2009/award/...   7634   
7390  http://techcrunch.com/2010/09/08/kno-raises-46...   8958   
7391  http://www.uncoached.com/category/why-i-miss-c...   8895   
7393                      

In [4]:
#cols = ['alchemy_category', 'alchemy_category_score', 'avglinksize', 'commonlinkratio_1', 'commonlinkratio_2', 'commonlinkratio_3', 'commonlinkratio_4', 'is_news', 'lengthyLinkDomain', 'linkwordscore', 'news_front_page', 'non_markup_alphanum_characters', 'numberOfLinks', 'numwords_in_url', 'parametrizedLinkRatio', 'spelling_errors_ratio', 'label']
header = [x for x in useful_df]
cols = [header[-1]]+header[3:-1]
data_df = useful_df[cols]
data_df[:2]

label alchemy_category alchemy_category_score  avglinksize  \
0      0         business               0.789131     2.055556   
1      1       recreation               0.574147     3.677966   

   commonlinkratio_1  commonlinkratio_2  commonlinkratio_3  commonlinkratio_4  \
0           0.676471           0.205882           0.047059           0.023529   
1           0.508021           0.288770           0.213904           0.144385   

   compression_ratio  embed_ratio          ...            image_ratio  \
0           0.443783          0.0          ...               0.003883   
1           0.468649          0.0          ...               0.088652   

   is_news  lengthyLinkDomain  linkwordscore  news_front_page  \
0        1                  1             24                0   
1        1                  1             40                0   

  non_markup_alphanum_characters  numberOfLinks  numwords_in_url  \
0                           5424            170                8   
1                           4973            187                9   

  parametrizedLinkRatio  spelling_errors_ratio  
0              0.152941               0.079130  
1              0.181818               0.125448  

[2 rows x 24 columns]

In [5]:
df = pd.get_dummies(data=data_df, columns=['alchemy_category']).astype(float)
df[:2]

label  alchemy_category_score  avglinksize  commonlinkratio_1  \
0    0.0                0.789131     2.055556           0.676471   
1    1.0                0.574147     3.677966           0.508021   

   commonlinkratio_2  commonlinkratio_3  commonlinkratio_4  compression_ratio  \
0           0.205882           0.047059           0.023529           0.443783   
1           0.288770           0.213904           0.144385           0.468649   

   embed_ratio  framebased            ...             \
0          0.0         0.0            ...              
1          0.0         0.0            ...              

   alchemy_category_culture_politics  alchemy_category_gaming  \
0                                0.0                      0.0   
1                                0.0                      0.0   

   alchemy_category_health  alchemy_category_law_crime  \
0                      0.0                         0.0   
1                      0.0                         0.0   

   alchemy_category_recreation  alchemy_category_religion  \
0                          0.0                        0.0   
1                          1.0                        0.0   

   alchemy_category_science_technology  alchemy_category_sports  \
0                                  0.0                      0.0   
1                                  0.0                      0.0   

   alchemy_category_unknown  alchemy_category_weather  
0                       0.0                       0.0  
1                       0.0                       0.0  

[2 rows x 36 columns]

In [6]:
ndarray = df.values
ndarray.shape

(3566, 36)

In [7]:
Label = ndarray[:, 0]
Features = ndarray[:,1:]

In [8]:
Label.shape

(3566,)

In [9]:
Label[:2]

array([0., 1.])

In [10]:
Features.shape

(3566, 35)

In [11]:
Features[:2]

array([[7.89131000e-01, 2.05555556e+00, 6.76470588e-01, 2.05882353e-01,
        4.70588240e-02, 2.35294120e-02, 4.43783175e-01, 0.00000000e+00,
        0.00000000e+00, 9.07738100e-02, 0.00000000e+00, 2.45831182e-01,
        3.88349500e-03, 1.00000000e+00, 1.00000000e+00, 2.40000000e+01,
        0.00000000e+00, 5.42400000e+03, 1.70000000e+02, 8.00000000e+00,
        1.52941176e-01, 7.91295750e-02, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.74147000e-01, 3.67796610e+00, 5.08021390e-01, 2.88770053e-01,
        2.13903743e-01, 1.44385027e-01, 4.68648998e-01, 0.00000000e+00,
        0.00000000e+00, 9.87074030e-02, 0.00000000e+00, 2.03489628e-01,
        8.86524820e-02, 1.00000000e+00, 1.00000000e+00, 4.00000000e+01,
        0.00000000e+00, 4.97300000e+03, 1.87000000e+02, 9.00000000e+00,
       

In [12]:
from sklearn import preprocessing
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaledFeatures=minmax_scale.fit_transform(Features)
scaledFeatures[:2]

array([[0.77251289, 0.01272487, 0.67647059, 0.20946292, 0.04960254,
        0.02480127, 0.02113253, 0.82352941, 0.        , 0.2155878 ,
        0.        , 0.39591215, 0.0189412 , 0.        , 1.        ,
        0.24      , 0.        , 0.06167281, 0.05149299, 0.38095238,
        0.15294118, 0.07912957, 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.53995344, 0.02276836, 0.50802139, 0.29379214, 0.22546611,
        0.15218962, 0.02231662, 0.82352941, 0.        , 0.23443008,
        0.        , 0.29765395, 0.02054061, 0.        , 1.        ,
        0.4       , 0.        , 0.05654478, 0.05667276, 0.42857143,
        0.18181818, 0.12544803, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [13]:
msk = np.random.rand(len(df)) < 0.8
train_df = df[msk]
test_df = df[~msk]

In [14]:
print('total:',len(all_df),
      'train:',len(train_df),
      'test:',len(test_df))

total: 7395 train: 2851 test: 715
